# Generated by Django 4.1.3 on 2022-12-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingresar_usuario', models.CharField(default=None, max_length=150)),
                ('ingresar_cuenta_destino', models.IntegerField()),
                ('ingresar_monto', models.IntegerField()),
            ],
        ),
    ]
