# Generated by Django 4.1.3 on 2022-12-13 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='persona',
        ),
        migrations.DeleteModel(
            name='Transferencias',
        ),
        migrations.DeleteModel(
            name='Tarjeta',
        ),
    ]
