# Generated by Django 4.1.3 on 2022-12-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_tarjeta_persona_delete_transferencias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosgenerales',
            name='domicilio',
            field=models.CharField(max_length=50),
        ),
    ]
