# Generated by Django 4.1.3 on 2022-12-13 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_remove_tarjeta_persona_delete_transferencias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tarjeta', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('ccv', models.IntegerField()),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.datosgenerales')),
            ],
        ),
    ]
